name: Github Actions

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: yarn ci

      - name: Linting
        run: yarn lint

      - name: Run tests with code coverage
        run: yarn test:coverage
